package lk.ijse.dep.pharmacy.dao;

public enum DAOTypes {
    PATIENT,DOCTOR,SUPPLIER,DRUG_ITEM,ORDER,ORDER_DETAIL,QUERY,LOCATION,BATCH,STOCK,GRN,GRN_DETAIL,PAYMENT,PRESCRIPTION,PRESCRIPTION_DETAIL,USER,USER_ROLE
}
